# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('icerik', models.TextField()),
                ('olusturma_tarih', models.DateTimeField()),
            ],
        ),
    ]
